In [1]:
#import libraries
import pandas as pd
#pd.set_option('display.max_columns', 100)
#pd.set_option('display.max_rows', 100)

In [2]:
#import dataset
poverty = pd.read_fwf('poverty rate est19-va.txt', sep=" ", header=None)
poverty.head()

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,51,0,822944,805003,840885,9.9,9.7,10.1,242806,232710,...,68257.0,63192.0,73322.0,13.9,12.9,14.9,Virginia,VA,est19-va.txt,16NOV2020
1,51,1,5225,4026,6424,16.4,12.6,20.2,1867,1377,...,NaN,NaN,NaN,NaN,NaN,NaN,Accomack County,VA,est19-va.txt,16NOV2020
2,51,3,6882,5510,8254,6.7,5.4,8.0,1559,1043,...,NaN,NaN,NaN,NaN,NaN,NaN,Albemarle County,VA,est19-va.txt,16NOV2020
3,51,5,1680,1255,2105,11.5,8.6,14.4,496,335,...,NaN,NaN,NaN,NaN,NaN,NaN,Alleghany County,VA,est19-va.txt,16NOV2020
4,51,7,1211,901,1521,9.3,6.9,11.7,370,249,...,NaN,NaN,NaN,NaN,NaN,NaN,Amelia County,VA,est19-va.txt,16NOV2020

In [3]:
#extract necessary columns
Poverty_est = poverty[[0, 1, 5, 29, 30, 31]]
Poverty_est.head()

   0   1     5                 29  30            31
0  51   0   9.9          Virginia  VA  est19-va.txt
1  51   1  16.4   Accomack County  VA  est19-va.txt
2  51   3   6.7  Albemarle County  VA  est19-va.txt
3  51   5  11.5  Alleghany County  VA  est19-va.txt
4  51   7   9.3     Amelia County  VA  est19-va.txt

In [4]:
#Add column names
Poverty_est.columns = ['FIPS State code', 'FIPS county code', 'Est%_poverty_all', 'County', 'State_code', 'Data-created']

In [5]:
#drop first row of Virginia totals
Poverty_est.drop(0, axis=0, inplace=True)

/Users/sarasharick/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4170: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [7]:
#Sort County alphabetically
Poverty_est = Poverty_est.sort_values(by=['County'], ascending=True)
Poverty_est.head(10)

,FIPS State code,FIPS county code,Est%_poverty_all,County,State_code,Data-created
1,51,1,16.4,Accomack County,VA,est19-va.txt
2,51,3,6.7,Albemarle County,VA,est19-va.txt
96,51,510,8.6,Alexandria city,VA,est19-va.txt
3,51,5,11.5,Alleghany County,VA,est19-va.txt
4,51,7,9.3,Amelia County,VA,est19-va.txt
5,51,9,12.0,Amherst County,VA,est19-va.txt
6,51,11,12.6,Appomattox County,VA,est19-va.txt
7,51,13,7.6,Arlington County,VA,est19-va.txt
8,51,15,7.3,Augusta County,VA,est19-va.txt
9,51,17,9.9,Bath County,VA,est19-va.txt

In [8]:
#Save cleaned dataset
Poverty_est.to_csv('Poverty_est_wk8.csv')

In [9]:
#Import dataset and review
demographics = pd.read_excel('County demograhic data.xlsx', header=1)
demographics.head()

,FIPS,State,County,Life Expectancy,95% CI - Low,95% CI - High,Life Expectancy (AIAN),Life Expectancy (AIAN) 95% CI - Low,Life Expectancy (AIAN) 95% CI - High,Life Expectancy (Asian),...,% Hispanic,# Non-Hispanic White,% Non-Hispanic White,# Not Proficient in English,% Not Proficient in English,95% CI - Low.19,95% CI - High.19,% Female,# Rural,% Rural
0,51000,Virginia,NaN,79.478556,79.415798,79.541315,NaN,NaN,NaN,NaN,...,9.637290,5234514,61.454656,209755,2.653844,2.588433,2.719254,50.800622,1963930,24.545983
1,51001,Virginia,Accomack,76.215010,75.154395,77.275626,NaN,NaN,NaN,NaN,...,9.339134,19438,59.971615,1297,4.205986,2.868678,5.543295,51.200173,33164,100.000000
2,51003,Virginia,Albemarle,83.004271,82.473261,83.535281,NaN,NaN,NaN,92.118032,...,5.949337,83280,76.601851,1833,1.820909,1.452787,2.189031,52.197428,44559,45.022734
3,51005,Virginia,Alleghany,76.253127,74.810257,77.695996,NaN,NaN,NaN,NaN,...,1.462106,13640,91.482227,11,0.075306,0.000000,0.671603,51.099933,8514,52.393846
4,51007,Virginia,Amelia,75.781118,74.109383,77.452854,NaN,NaN,NaN,NaN,...,2.858680,9652,74.171982,86,0.710157,0.000000,1.779426,50.695458,12690,100.000000

In [10]:
#extract necessary columns
demographics = demographics[['FIPS', 'State', 'County', 'Population', '% 65 and over', '% Black', '% American Indian & Alaska Native',
                            '% Asian', '% Native Hawaiian/Other Pacific Islander', '% Hispanic', '% Non-Hispanic White', '% Rural']]
demographics.head()

,FIPS,State,County,Population,% 65 and over,% Black,% American Indian & Alaska Native,% Asian,% Native Hawaiian/Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Rural
0,51000,Virginia,NaN,8517685,15.443175,19.106530,0.544855,6.915564,0.117379,9.637290,61.454656,24.545983
1,51001,Virginia,Accomack,32412,23.565346,27.971122,0.694187,0.780575,0.172776,9.339134,59.971615,100.000000
2,51003,Virginia,Albemarle,108718,18.624331,9.430821,0.383561,5.585092,0.092901,5.949337,76.601851,45.022734
3,51005,Virginia,Alleghany,14910,24.694836,4.600939,0.288397,0.288397,0.087190,1.462106,91.482227,52.393846
4,51007,Virginia,Amelia,13013,19.795589,20.387305,0.576347,0.614770,0.046108,2.858680,74.171982,100.000000

In [11]:
#Drop first row of Virginia totals and sort by county name
demographics.drop(0, axis=0, inplace=True)
demographics = demographics.sort_values(by=['County'], ascending=True)
demographics.head(10)

,FIPS,State,County,Population,% 65 and over,% Black,% American Indian & Alaska Native,% Asian,% Native Hawaiian/Other Pacific Islander,% Hispanic,% Non-Hispanic White,% Rural
1,51001,Virginia,Accomack,32412,23.565346,27.971122,0.694187,0.780575,0.172776,9.339134,59.971615,100.000000
2,51003,Virginia,Albemarle,108718,18.624331,9.430821,0.383561,5.585092,0.092901,5.949337,76.601851,45.022734
96,51510,Virginia,Alexandria City,160530,11.502523,21.999626,0.634772,6.730829,0.143898,16.748894,51.752320,0.000000
3,51005,Virginia,Alleghany,14910,24.694836,4.600939,0.288397,0.288397,0.087190,1.462106,91.482227,52.393846
4,51007,Virginia,Amelia,13013,19.795589,20.387305,0.576347,0.614770,0.046108,2.858680,74.171982,100.000000
5,51009,Virginia,Amherst,31666,21.161498,18.875134,0.909493,0.549485,0.044211,2.595844,74.894208,63.663339
6,51011,Virginia,Appomattox,15841,20.705764,18.856133,0.321949,0.340888,0.044189,1.647623,76.807020,100.000000
7,51013,Virginia,Arlington,237521,10.613377,9.038359,0.649206,11.033972,0.129252,15.790183,61.215219,0.000000
8,51015,Virginia,Augusta,75457,21.041123,4.378653,0.243847,0.670581,0.038432,2.875810,90.577415,66.437966
9,51017,Virginia,Bath,4292,27.656104,4.543336,0.209692,0.442684,0.000000,2.399814,91.076421,100.000000

In [12]:
#Save cleaned dataset
demographics.to_csv('demographics_wk8.csv')

In [13]:
#Import dataset
elections = pd.read_csv('2020 November General.csv')
elections.head()

,CandidateUid,FirstName,MiddleName,LastName,Suffix,TOTAL_VOTES,Party,WriteInVote,LocalityUid,LocalityCode,...,PrecinctName,DistrictUid,DistrictType,DistrictName,OfficeUid,OfficeTitle,ElectionUid,ElectionType,ElectionDate,ElectionName
0,NaN,NaN,NaN,WRITE IN VOTES,NaN,1.0,NaN,1,{15B7E141-2D1D-44C2-A50A-AAE021BC9B7D},1,...,# AB - Central Absentee Precinct,{7834A502-161B-48C5-B815-E8DC67D51358},Town,PAINTER,{008C81A4-9FDC-4628-8DCA-2247996831DA},Mayor - Painter,{5BEEA701-3272-4452-AE08-BFDF24F0D41C},General,2020-11-03 00:00:00,2020 November General
1,NaN,NaN,NaN,WRITE IN VOTES,NaN,2.0,NaN,1,{15B7E141-2D1D-44C2-A50A-AAE021BC9B7D},1,...,# AB - Central Absentee Precinct,{05BBA99B-D90A-4413-A142-8163C13316D2},Town,PARKSLEY,{5A7D053B-A5B5-43B2-91A7-4D92D7690888},Member Town Council - Parksley,{5BEEA701-3272-4452-AE08-BFDF24F0D41C},General,2020-11-03 00:00:00,2020 November General
2,NaN,NaN,NaN,WRITE IN VOTES,NaN,3.0,NaN,1,{15B7E141-2D1D-44C2-A50A-AAE021BC9B7D},1,...,# AB - Central Absentee Precinct,{8967B9DD-E94E-4964-A919-30E520165984},Congressional,02,{72E39A01-83E7-4A1F-A743-8A0241C16F23},Member House of Representatives,{5BEEA701-3272-4452-AE08-BFDF24F0D41C},General,2020-11-03 00:00:00,2020 November General
3,NaN,NaN,NaN,WRITE IN VOTES,NaN,3.0,NaN,1,{15B7E141-2D1D-44C2-A50A-AAE021BC9B7D},1,...,# AB - Central Absentee Precinct,{626EAF74-8687-417C-9FB1-CEAD2B031804},Town,ONLEY,{D11D5A1E-D48E-4F7B-8B04-5E53D460FDC4},Member Town Council - Onley,{5BEEA701-3272-4452-AE08-BFDF24F0D41C},General,2020-11-03 00:00:00,2020 November General
4,NaN,NaN,NaN,WRITE IN VOTES,NaN,3.0,NaN,1,{15B7E141-2D1D-44C2-A50A-AAE021BC9B7D},1,...,# AB - Central Absentee Precinct,{7834A502-161B-48C5-B815-E8DC67D51358},Town,PAINTER,{CFC120D3-A178-4C5C-9257-791A0A541478},Member Town Council - Painter,{5BEEA701-3272-4452-AE08-BFDF24F0D41C},General,2020-11-03 00:00:00,2020 November General

In [14]:
#review office titles to find relevant office
elections['OfficeTitle'].value_counts()

President and Vice President       11100
Member United States Senate         8325
Member House of Representatives     8126
Mayor                               1582
Member City Council                 1355
                                   ...
Mayor - Nassawadox                     6
Mayor - Eastville                      6
Member Town Council - Boykins          6
Mayor - Timberville                    6
Mayor - Bloxom                         5
Name: OfficeTitle, Length: 118, dtype: int64

In [15]:
#Filter for preferred office
elections_p = elections[elections['OfficeTitle'] == 'President and Vice President']

In [16]:
#loop over localities for sum of votes for each locality
for LocalityName in elections_p:
    total_votes = elections_p.groupby('LocalityName').sum('TOTAL_VOTES')

print(total_votes)

                   TOTAL_VOTES  WriteInVote  LocalityCode
LocalityName
ACCOMACK COUNTY        16962.0           18            72
ALBEMARLE COUNTY       64657.0           32           384
ALEXANDRIA CITY        82521.0           32         65280
ALLEGHANY COUNTY        8203.0           14           280
AMELIA COUNTY           7894.0            7           196
...                        ...          ...           ...
WILLIAMSBURG CITY       6890.0            4         13280
WINCHESTER CITY        12113.0            8         26880
WISE COUNTY            16615.0           14         10920
WYTHE COUNTY           15073.0           13         10244
YORK COUNTY            38791.0           15         11940

[133 rows x 3 columns]

In [17]:
#Loop over localities for sum of votes by party in each locality
for LocalityName in elections_p:
    party_votes = elections_p.groupby(['LocalityName', 'Party']).sum('TOTAL_VOTES').reset_index()
print(party_votes)

         LocalityName        Party  TOTAL_VOTES  WriteInVote  LocalityCode
0     ACCOMACK COUNTY   Democratic       7578.0            0            18
1     ACCOMACK COUNTY  Libertarian        188.0            0            18
2     ACCOMACK COUNTY   Republican       9172.0            0            18
3    ALBEMARLE COUNTY   Democratic      42466.0            0            96
4    ALBEMARLE COUNTY  Libertarian       1014.0            0            96
..                ...          ...          ...          ...           ...
394      WYTHE COUNTY  Libertarian        170.0            0          2561
395      WYTHE COUNTY   Republican      11733.0            0          2561
396       YORK COUNTY   Democratic      17683.0            0          2985
397       YORK COUNTY  Libertarian        680.0            0          2985
398       YORK COUNTY   Republican      20241.0            0          2985

[399 rows x 5 columns]

In [18]:
#create new dataframe 
Votes = pd.DataFrame(columns=['Total', 'Dem_votes', 'Rep_votes', 'Lib_votes', 'Dem_votes%', 'Rep_votes%', 'Lib_votes%'])

In [19]:
#populate vote totals column
Votes['Total'] = total_votes['TOTAL_VOTES']

In [20]:
#review to ensure all parties have same number of entries
party_votes['Party'].value_counts()

Republican     133
Democratic     133
Libertarian    133
Name: Party, dtype: int64

In [21]:
#filter for party, merge with new dataframe, populate party column, drop extra column
democrat_votes = party_votes[['LocalityName', 'TOTAL_VOTES']].where(party_votes['Party'] == 'Democratic').dropna()
Votes = Votes.merge(democrat_votes, how='left', on='LocalityName')
Votes['Dem_votes'] = Votes['TOTAL_VOTES']
Votes.drop(['TOTAL_VOTES'], axis=1, inplace=True)

In [22]:
republican_votes = party_votes[['LocalityName', 'TOTAL_VOTES']].where(party_votes['Party'] == 'Republican').dropna()
Libertarian_votes = party_votes[['LocalityName', 'TOTAL_VOTES']].where(party_votes['Party'] == 'Libertarian').dropna()

In [23]:
Votes = Votes.merge(republican_votes, how='left', on='LocalityName')
Votes['Rep_votes'] = Votes['TOTAL_VOTES']
Votes.drop(['TOTAL_VOTES'], axis=1, inplace=True)

In [24]:
Votes = Votes.merge(Libertarian_votes, how='left', on='LocalityName')
Votes['Lib_votes'] = Votes['TOTAL_VOTES']
Votes.drop(['TOTAL_VOTES'], axis=1, inplace=True)
Votes

,LocalityName,Total,Dem_votes,Rep_votes,Lib_votes,Dem_votes%,Rep_votes%,Lib_votes%
0,ACCOMACK COUNTY,16962.0,7578.0,9172.0,188.0,NaN,NaN,NaN
1,ALBEMARLE COUNTY,64657.0,42466.0,20804.0,1014.0,NaN,NaN,NaN
2,ALEXANDRIA CITY,82521.0,66240.0,14544.0,1022.0,NaN,NaN,NaN
3,ALLEGHANY COUNTY,8203.0,2243.0,5859.0,89.0,NaN,NaN,NaN
4,AMELIA COUNTY,7894.0,2411.0,5390.0,80.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
128,WILLIAMSBURG CITY,6890.0,4790.0,1963.0,92.0,NaN,NaN,NaN
129,WINCHESTER CITY,12113.0,6610.0,5221.0,213.0,NaN,NaN,NaN
130,WISE COUNTY,16615.0,3110.0,13366.0,108.0,NaN,NaN,NaN
131,WYTHE COUNTY,15073.0,3143.0,11733.0,170.0,NaN,NaN,NaN
132,YORK COUNTY,38791.0,17683.0,20241.0,680.0,NaN,NaN,NaN

In [25]:
#replace all NaNs with 0
Votes['Dem_votes'].replace('NaN', 0, inplace=True)
Votes['Rep_votes'].replace('NaN', 0, inplace=True)
Votes['Lib_votes'].replace('NaN', 0, inplace=True)

In [26]:
#calculate vote percentages by party
Votes['Dem_votes%'] = Votes['Dem_votes']/Votes['Total'].round(2)*100
Votes['Rep_votes%'] = Votes['Rep_votes']/Votes['Total'].round(2)*100
Votes['Lib_votes%'] = Votes['Lib_votes']/Votes['Total'].round(2)*100

In [27]:
#re-order counties and cities with same name to have county first to match other datasets
fxci_copy = Votes.iloc[37].copy()
fxco_copy = Votes.iloc[38].copy()
Votes.iloc[37] = fxco_copy
Votes.iloc[38] = fxci_copy

frci_copy = Votes.iloc[43].copy()
frco_copy = Votes.iloc[44].copy()
Votes.iloc[43] = frco_copy
Votes.iloc[44] = frci_copy

rici_copy = Votes.iloc[104].copy()
rico_copy = Votes.iloc[105].copy()
Votes.iloc[104] = rico_copy
Votes.iloc[105] = rici_copy

roci_copy = Votes.iloc[106].copy()
roco_copy = Votes.iloc[107].copy()
Votes.iloc[106] = roco_copy
Votes.iloc[107] = roci_copy

In [28]:
Votes

,LocalityName,Total,Dem_votes,Rep_votes,Lib_votes,Dem_votes%,Rep_votes%,Lib_votes%
0,ACCOMACK COUNTY,16962.0,7578.0,9172.0,188.0,44.676335,54.073812,1.108360
1,ALBEMARLE COUNTY,64657.0,42466.0,20804.0,1014.0,65.678890,32.175944,1.568276
2,ALEXANDRIA CITY,82521.0,66240.0,14544.0,1022.0,80.270477,17.624605,1.238473
3,ALLEGHANY COUNTY,8203.0,2243.0,5859.0,89.0,27.343655,71.425088,1.084969
4,AMELIA COUNTY,7894.0,2411.0,5390.0,80.0,30.542184,68.279706,1.013428
...,...,...,...,...,...,...,...,...
128,WILLIAMSBURG CITY,6890.0,4790.0,1963.0,92.0,69.521045,28.490566,1.335269
129,WINCHESTER CITY,12113.0,6610.0,5221.0,213.0,54.569471,43.102452,1.758441
130,WISE COUNTY,16615.0,3110.0,13366.0,108.0,18.718026,80.445381,0.650015
131,WYTHE COUNTY,15073.0,3143.0,11733.0,170.0,20.851854,77.841173,1.127844
132,YORK COUNTY,38791.0,17683.0,20241.0,680.0,45.585316,52.179629,1.752984

In [29]:
#Save cleaned dataset
Votes.to_csv('votes_wk8.csv')

In [30]:
#Import dataset
cases = pd.read_csv('VDH-COVID-19-PublicUseDataset-Cases-4.csv')
cases.head(10)

,Report Date,FIPS,Locality,VDH Health District,Total Cases,Hospitalizations,Deaths
0,03/17/2020,51001,Accomack,Eastern Shore,0,0,0
1,03/17/2020,51003,Albemarle,Thomas Jefferson,0,0,0
2,03/17/2020,51005,Alleghany,Alleghany,0,0,0
3,03/17/2020,51007,Amelia,Piedmont,0,0,0
4,03/17/2020,51009,Amherst,Central Virginia,0,0,0
5,03/17/2020,51011,Appomattox,Central Virginia,0,0,0
6,03/17/2020,51013,Arlington,Arlington,13,1,0
7,03/17/2020,51015,Augusta,Central Shenandoah,0,0,0
8,03/17/2020,51017,Bath,Central Shenandoah,0,0,0
9,03/17/2020,51019,Bedford,Central Virginia,0,0,0

In [31]:
#Group by locality and choose max for each locality
cases = cases.groupby('Locality').max('Total Cases')
cases = cases.reset_index()
cases.head(10)

     Locality   FIPS  Total Cases  Hospitalizations  Deaths
0    Accomack  51001         1579               117      25
1   Albemarle  51003         2469               123      29
2  Alexandria  51510         6660               413      83
3   Alleghany  51005          586                27      20
4      Amelia  51007          332                26       7
5     Amherst  51009         1221                39       8
6  Appomattox  51011          584                28       6
7   Arlington  51013         7975               634     168
8     Augusta  51015         2641                61      22
9        Bath  51017          111                 2       1

In [32]:
len(cases)

133

In [33]:
#re-order counties and cities with same name to have county first to match other datasets
frci_copy = cases.iloc[43].copy()
frco_copy = cases.iloc[44].copy()
cases.iloc[43] = frco_copy
cases.iloc[44] = frci_copy

rici_copy = cases.iloc[104].copy()
rico_copy = cases.iloc[105].copy()
cases.iloc[104] = rico_copy
cases.iloc[105] = rici_copy

roci_copy = cases.iloc[106].copy()
roco_copy = cases.iloc[107].copy()
cases.iloc[106] = roco_copy
cases.iloc[107] = roci_copy

In [34]:
#Save cleaned dataset
cases.to_csv('cases_wk8.csv')